version: "3"

services:

    wordpress:
      image: wordpress:4.9.5-fpm-alpine
      environment:
        WORDPRESS_DB_PASSWORD: example
      volumes:
        - wordpress_files:/var/www/html

    nginx:
      image: raulr/nginx-wordpress
      volumes:
        - wordpress_files:/var/www/html
      ports:
        - "8080:80"

    mysql:
      image: mysql
      environment:
        MYSQL_ROOT_PASSWORD: example

volumes:
  wordpress_files:
